# Auto-generated by calibration script
# Generated: 2026-02-08 16:28:45

import numpy as np

INTRINSIC_MAT = np.array(
[[286.5287556618,   0.          , 324.1554709939],
 [  0.          , 291.6808505443, 271.5985535634],
 [  0.          ,   0.          ,   1.          ]],
dtype=float
)

# OpenCV distortion coefficients:
# Typically [k1, k2, p1, p2, k3] (and sometimes more depending on model)
DISTORTION_COEFFS = np.array(
[-0.0130893276, -0.0076518965, -0.0084375531, -0.006684244 ,  0.0006938432],
dtype=float
)
